Parameters:
  KeyName:
    Description: The ssh keypair used to access the buildkite instances
    Type: AWS::EC2::KeyPair::KeyName
  BuildkiteOrgSlug:
    Description: Your Buildkite organization slug
    Type: String
  BuildkiteAgentToken:
    Description: Your Buildkite agent token from Buildkite.com
    Type: String
    NoEcho: true
  BuildkiteApiToken:
    Description: Your Buildkite api token from
    Type: String
    NoEcho: true
  ProvisionBucket:
    Description: An s3 bucket containing dockercfg and id_rsa_buildkite
    Type: String

Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ ec2.amazonaws.com ]
            Action: sts:AssumeRole
      Path: /

  IAMPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: InstancePolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - cloudwatch:PutMetricData
              - cloudformation:DescribeStackResource
            Resource: "*"
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:ListBucket
              - s3:ListBucketVersions
            Resource: "arn:aws:s3:::$(ProvisionBucket)/*"
      Roles:
        - $(IAMRole)

  IAMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: [ $(IAMRole) ]

  AgentLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      SecurityGroups: [ $(SecurityGroup) ]
      KeyName : $(KeyName)
      IamInstanceProfile: $(IAMInstanceProfile)
      InstanceType: m3.medium
      ImageId : ami-cf09e8a4 # Ubuntu 15.04, HVM
      UserData: !Base64 |
        #!/bin/bash -xv
        exec &>/home/ubuntu/boot.log
        tail -F /var/log/cfn-init.log /var/log/cfn-init-cmd.log &
        apt-get -y install python-setuptools && \
        easy_install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz && \
        /usr/local/bin/cfn-init -s $(AWS::StackId) -r AgentLaunchConfiguration --region $(AWS::Region)
        /usr/local/bin/cfn-signal -e \$? -r 'cfn-init finished' '$(AgentWaitHandle)'
    Metadata:
      AWS::CloudFormation::Authentication:
        S3AccessCreds:
          type: S3
          roleName: $(IAMRole)
          buckets: $(ProvisionBucket)
      AWS::CloudFormation::Init:
        config:
          files:
            "/home/ubuntu/.ssh/id_rsa":
              source: "https://s3.amazonaws.com/$(ProvisionBucket)/id_rsa_buildkite"
              mode: '000400'
              owner: ubuntu
              group: ubuntu
              authentication: S3AccessCreds
            "/home/ubuntu/.dockercfg":
              source: "https://s3.amazonaws.com/$(ProvisionBucket)/dockercfg"
              mode: '000400'
              owner: ubuntu
              group: ubuntu
              authentication: S3AccessCreds
            "/home/ubuntu/docker-compose.yml":
              content: |
                buildkite:
                  image: buildkite/agent:dind
                  privileged: true
                  environment:
                    - BUILDKITE_AGENT_TOKEN=$(BuildkiteAgentToken)
                    - BUILDKITE_AGENT_META_DATA=queue=elastic
                    - BUILDKITE_AGENT_NAME=elastic-%hostname-%n
                  volumes:
                    - /home/ubuntu/.ssh:/root/.ssh
                    - /home/ubuntu/.dockercfg:/root/.dockercfg
                  restart: always
              mode: '000600'
              owner: ubuntu
              group: ubuntu
          commands:
            01-install-docker:
              command: |
                curl -sSL https://get.docker.com/ | sh
                usermod -aG docker ubuntu
                systemctl enable docker
                systemctl start docker
            02-install-docker-compose:
              command: |
                curl -L https://github.com/docker/compose/releases/download/1.2.0/docker-compose-Linux-x86_64 > /usr/local/bin/docker-compose
                chmod +x /usr/local/bin/docker-compose
            03-install-buildkite:
              command: |
                docker-compose -f /home/ubuntu/docker-compose.yml up -d buildkite

  AgentAutoScaleGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: !GetAZs ""
      LaunchConfigurationName: $(AgentLaunchConfiguration)
      MinSize: 1
      MaxSize: 1
      Tags:
        - Key: Name
          Value: buildkite-agent
          PropagateAtLaunch: true

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable access to SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  AgentWaitHandle:
    Type: AWS::CloudFormation::WaitConditionHandle

  AgentWaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    Properties:
      Handle: $(AgentWaitHandle)
      Count : 1
      Timeout: 600