
Resources:
  AgentScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: $(AgentAutoScaleGroup)
      Cooldown: 10
      ScalingAdjustment: 1

  AgentScaleDownPolicy:
    Type : AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: $(AgentAutoScaleGroup)
      Cooldown : 10
      ScalingAdjustment : -1

  CPUAlarmHigh:
   Type: AWS::CloudWatch::Alarm
   Properties:
      AlarmDescription: Scale-up if CPU > 40% for 5 minutes
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 40
      AlarmActions: [ $(AgentScaleUpPolicy) ]
      Dimensions:
        - Name: AutoScalingGroupName
          Value: $(AgentAutoScaleGroup)
      ComparisonOperator: GreaterThanThreshold

  CPUAlarmLow:
   Type: AWS::CloudWatch::Alarm
   Properties:
      AlarmDescription: Scale-down if CPU < 5% for 5 minutes
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      AlarmActions: [ $(AgentScaleDownPolicy) ]
      Dimensions:
        - Name: AutoScalingGroupName
          Value: $(AgentAutoScaleGroup)
      ComparisonOperator: LessThanThreshold


  ScheduledJobsAlarmHigh:
   Type: AWS::CloudWatch::Alarm
   Properties:
      AlarmDescription: Scale-up if ScheduledJobs > 0 for 1 minute
      MetricName: ScheduledJobsCount
      Namespace: Buildkite
      Statistic: Average
      Period: 60
      EvaluationPeriods: 1
      Threshold: 0
      AlarmActions: [ $(AgentScaleUpPolicy) ]
      Dimensions:
        - Name: Queue
          Value: $(BuildkiteQueue)
      ComparisonOperator: GreaterThanThreshold

  ScheduledJobsAlarmLow:
   Type: AWS::CloudWatch::Alarm
   Properties:
      AlarmDescription: Scale-down if ScheduledJobs == 0 for 1 minute
      MetricName: ScheduledJobsCount
      Namespace: Buildkite
      Statistic: Average
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      AlarmActions: [ $(AgentScaleDownPolicy) ]
      Dimensions:
        - Name: AutoScalingGroupName
          Value: $(AgentAutoScaleGroup)
      ComparisonOperator: LessThanThreshold
