
Resources:
  AgentScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: $(AgentAutoScaleGroup)
      Cooldown: 60
      ScalingAdjustment: 1

  AgentScaleDownPolicy:
    Type : AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: $(AgentAutoScaleGroup)
      Cooldown : 60
      ScalingAdjustment : -1

  CPUAlarmHigh:
   Type: AWS::CloudWatch::Alarm
   Properties:
      AlarmDescription: Scale-up if CPU > 90% for 10 minutes
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 90
      AlarmActions: [ $(AgentScaleUpPolicy) ]
      Dimensions:
        - Name: AutoScalingGroupName
          Value: $(AgentAutoScaleGroup)
      ComparisonOperator: GreaterThanThreshold

  CPUAlarmLow:
   Type: AWS::CloudWatch::Alarm
   Properties:
      AlarmDescription: Scale-down if CPU < 70% for 10 minutes
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 70
      AlarmActions: [ $(AgentScaleDownPolicy) ]
      Dimensions:
        - Name: AutoScalingGroupName
          Value: $(AgentAutoScaleGroup)
      ComparisonOperator: LessThanThreshold