Parameters:
  KeyName:
    Description: The ssh keypair used to access the buildkite instances
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Description: The EC2 instance type used for buildkite instances
    Type: String
    Default: m3.medium
  BuildkiteOrgSlug:
    Description: Your Buildkite organization slug
    Type: String
  BuildkiteAgentToken:
    Description: Your Buildkite agent token from Buildkite.com
    Type: String
    NoEcho: true
  BuildkiteApiToken:
    Description: Your Buildkite api token from
    Type: String
    NoEcho: true
  ProvisionBucket:
    Description: An s3 bucket containing a provision tarball and github keys
    Type: String
  ProvisionTarball:
    Description: A tarball of provision scripts in an S3 bucket
    Type: String

Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ ec2.amazonaws.com ]
            Action: sts:AssumeRole
      Path: /

  IAMPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: InstancePolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - cloudwatch:PutMetricData
              - cloudformation:DescribeStackResource
            Resource: "*"
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:ListBucket
              - s3:ListBucketVersions
            Resource: "arn:aws:s3:::$(ProvisionBucket)/*"
      Roles:
        - $(IAMRole)

  IAMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: [ $(IAMRole) ]

  MetricInstance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups: [ $(SecurityGroup) ]
      KeyName : $(KeyName)
      IamInstanceProfile: $(IAMInstanceProfile)
      InstanceType: t1.micro
      ImageId : ami-1ccae774 # Amazon Linux 2015.03
      UserData: !Base64 |
        #!/bin/bash -xv
        exec &>/home/ec2-user/boot.log
        tail -F /var/log/cfn-init.log &
        /opt/aws/bin/cfn-init -s $(AWS::StackId) -r MetricInstance --region $(AWS::Region)
        /opt/aws/bin/cfn-signal -e \$? -r 'cfn-init finished' '$(MetricWaitHandle)'
      Tags:
        - Key: Name
          Value: buildkite-metrics

    Metadata:
      AWS::CloudFormation::Authentication:
        S3AccessCreds:
          type: S3
          roleName: $(IAMRole)
          buckets: $(ProvisionBucket)
      AWS::CloudFormation::Init:
        config:
          sources:
            "/root/provision": https://s3.amazonaws.com/$(ProvisionBucket)/$(ProvisionTarball)
          files:
            "/etc/buildkite-metrics.env":
              content: |
                BUILDKITE_ORG_SLUG=$(BuildkiteOrgSlug)
                BUILDKITE_API_ACCESS_TOKEN=$(BuildkiteApiToken)
                AWS_DEFAULT_REGION=$(AWS::Region)
              mode: 000644
              owner: root
              group: root
          commands:
            provision:
              command: /root/provision/provision-metrics
              env:
                 PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  AgentLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      SecurityGroups: [ $(SecurityGroup) ]
      KeyName : $(KeyName)
      IamInstanceProfile: $(IAMInstanceProfile)
      InstanceType: $(InstanceType)
      ImageId : ami-5ccae734 # Amazon Linux 2015.03
      UserData: !Base64 |
        #!/bin/bash -xv
        exec &>/home/ec2-user/boot.log
        tail -F /var/log/cfn-init.log &
        /opt/aws/bin/cfn-init -s $(AWS::StackId) -r AgentLaunchConfiguration --region $(AWS::Region)
        /opt/aws/bin/cfn-signal -e \$? -r 'cfn-init finished' '$(AgentWaitHandle)'
    Metadata:
      AWS::CloudFormation::Authentication:
        S3AccessCreds:
          type: S3
          roleName: $(IAMRole)
          buckets: $(ProvisionBucket)
      AWS::CloudFormation::Init:
        config:
          sources:
            "/root/provision": https://s3.amazonaws.com/$(ProvisionBucket)/$(ProvisionTarball)
          files:
            "/root/provision/id_rsa_buildkite":
              source: "https://s3.amazonaws.com/$(ProvisionBucket)/id_rsa_buildkite"
              mode: "000600"
              owner: ec2-user
              group: ec2-user
              authentication: S3AccessCreds
          commands:
            provision:
              command: /root/provision/provision-agent
              env:
                 BUILDKITE_AGENT_TOKEN: $(BuildkiteAgentToken)
                 PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  AgentAutoScaleGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: !GetAZs ""
      LaunchConfigurationName: $(AgentLaunchConfiguration)
      MinSize: 1
      MaxSize: 1
      Tags:
        - Key: Name
          Value: buildkite-agent
          PropagateAtLaunch: true

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable access to SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MetricWaitHandle:
    Type: AWS::CloudFormation::WaitConditionHandle

  MetricWaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    Properties:
      Handle: $(MetricWaitHandle)
      Count : 1
      Timeout: 600

  AgentWaitHandle:
    Type: AWS::CloudFormation::WaitConditionHandle

  AgentWaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    Properties:
      Handle: $(AgentWaitHandle)
      Count : 1
      Timeout: 600