## Provides the infrastructure for a scalable buildkite cluster

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Buildkite Configuration
        Parameters:
        - BuildkiteAgentRelease
        - BuildkiteAgentToken
        - BuildkiteQueue
        - BuildkiteOrgSlug
        - BuildkiteApiAccessToken

      - Label:
          default: Network Configuration
        Parameters:
        - VpcId
        - Subnets
        - AvailabilityZones
        - SecurityGroupId
        - ManagedPolicyArns

      - Label:
          default: Instance Configuration
        Parameters:
        - ImageId
        - InstanceType
        - AgentsPerInstance
        - KeyName
        - SpotPrice
        - SecretsBucket
        - ArtifactsBucket
        - AuthorizedUsersUrl
        - BootstrapScriptUrl
        - RootVolumeSize
        - AssociatePublicIpAddress

      - Label:
          default: Auto-scaling Configuration
        Parameters:
        - DesiredSize
        - MinSize
        - MaxSize
        - ScaleUpAdjustment
        - ScaleDownAdjustment

      - Label:
          default: Docker Registry Configuration
        Parameters:
        - ECRAccessPolicy

Parameters:
  KeyName:
    Description: The ssh keypair used to access the buildkite instances
    Type: AWS::EC2::KeyPair::KeyName
    MinLength: 1

  BuildkiteAgentRelease:
    Type: String
    AllowedValues:
      - stable
      - beta
      - edge
    Default: "stable"

  BuildkiteAgentToken:
    Description: Buildkite Agent token
    Type: String
    NoEcho: true
    MinLength: 1

  BuildkiteOrgSlug:
    Description: Buildkite organization slug (required for autoscaling metrics)
    Type: String
    MinLength: 1

  BuildkiteApiAccessToken:
    Description: Buildkite API access token with read_pipelines, read_builds and read_agents (required for autoscaling metrics)
    Type: String
    NoEcho: true
    MinLength: 1

  BuildkiteQueue:
    Description: Queue name that agents will use, targeted in pipeline steps using "queue={value}"
    Type: String
    Default: default
    MinLength: 1

  AgentsPerInstance:
    Description: Number of Buildkite agents to run on each instance
    Type: Number
    Default: 1
    MinValue: 1

  SecretsBucket:
    Description: Optional - name of an existing S3 bucket containing pipeline secrets
    Type: String
    Default: ""

  ArtifactsBucket:
    Description: Optional - name of an existing S3 bucket for build artifact storage
    Type: String
    Default: ""

  AuthorizedUsersUrl:
    Description: Optional - http(s) url or S3 path to periodically download ssh authorized_keys from
    Type: String
    Default: ""

  BootstrapScriptUrl:
    Description: Optional - http(s) url or S3 url to run on each instance during boot
    Type: String
    Default: ""

  VpcId:
    Type: String
    Description: Optional - VPC Id of existing VPC. Leave blank to have a new VPC created
    Default: ""

  Subnets:
    Type: CommaDelimitedList
    Description: Optional - Comma separated list of three existing VPC Subnet Ids where EC2 instances will run.  Required if setting VpcId.
    Default: ""

  AvailabilityZones:
    Type: CommaDelimitedList
    Description: Optional - defines the AZs that subnets are created in if Subnets parameter is not specified.
    Default: ""

  InstanceType:
    Description: The type of instance to use for the instances
    Type: String
    Default: t2.nano
    MinLength: 1

  SpotPrice:
    Description: Optional - Spot price to use for the instances. 0 means normal (non-spot) instances are used
    Type: String
    Default: 0

  MaxSize:
    Description: The maximum number of instances to launch
    Type: Number
    Default: 10
    MinValue: 1

  MinSize:
    Description: The minumum number of instances to launch
    Type: Number
    Default: 0

  ScaleUpAdjustment:
    Description: The number of instances to adjust by on each scale up event (ScheduledJobsCount > 0 for 1 min)
    Type: Number
    Default: 5
    MinValue: 0

  ScaleDownAdjustment:
    Description: The number of instances to remove on each scale down event (UnfinishedJobs == 0 for 30 mins)
    Type: Number
    Default: -1
    MaxValue: 0

  RootVolumeSize:
    Description: Size of EBS volume for root filesystem in GB.
    Type: Number
    Default: 250
    MinValue: 10

  SecurityGroupId:
    Type: String
    Description: Optional - Existing security group to associate the container instances. Creates one by default.
    Default: ""

  ImageId:
    Type: String
    Description: Optional - The AMI to use, otherwise uses the mapping built in
    Default: ""

  ManagedPolicyARN:
    Type: String
    Description: Optional - ARN of an existing managed IAM policy that will be attached to the instance role
    Default: ""

  ECRAccessPolicy:
    Type: String
    Description: Optional - The ECR access policy to give container instances
    AllowedValues:
      - none
      - readonly
      - poweruser
      - full
    Default: "none"

  AssociatePublicIpAddress:
    Type: String
    Description: Optional - Associate a public IP address with the agent instance (default true)
    AllowedValues:
      - true
      - false
    Default: "true"

Conditions:
    UseSpotInstances:
      !Not [ !Equals [ $(SpotPrice), 0 ] ]

    CreateVpcResources:
      !Equals [ $(VpcId), "" ]

    CreateSecurityGroup:
      !Equals [ $(SecurityGroupId), "" ]

    UseSpecifiedAvailabilityZones:
      !Not [ !Equals [ !Join [ "", $(AvailabilityZones) ], "" ]  ]

    UseSecretsBucket:
      !Not [ !Equals [ $(SecretsBucket), "" ] ]

    UseArtifactsBucket:
      !Not [ !Equals [ $(ArtifactsBucket), "" ] ]

    UseDefaultAMI:
      !Equals [ $(ImageId), "" ]

    UseManagedPolicyARN:
      !Not [ !Equals [ $(ManagedPolicyARN), "" ] ]

    UseECR:
      !Not [ !Equals [ $(ECRAccessPolicy), "none" ] ]

    UseAutoscaling:
      !Not [ !Equals [ $(MaxSize), $(MinSize) ] ]

    CreateMetricsStack:
      !And [ Condition: UseAutoscaling, !Not [ !Equals [ $(BuildkiteApiAccessToken), "" ] ] ]

    AllowZeroInstancesDuringScaling:
      !Equals [ $(MaxSize), "1" ]

Mappings:
  ECRManagedPolicy:
    none      : { Policy: '' }
    readonly  : { Policy: 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly' }
    poweruser : { Policy: 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser' }
    full      : { Policy: 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess' }

Resources:
  # Allow ec2 instances to assume a role and be granted the IAMPolicies
  IAMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: [ $(IAMRole) ]

  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "$(AWS::StackName)-Role"
      ManagedPolicyArns:
        - !If [ UseManagedPolicyARN, $(ManagedPolicyARN), '$(AWS::NoValue)' ]
        - !If [ UseECR, '$(ECRManagedPolicy[$(ECRAccessPolicy)][Policy])', '$(AWS::NoValue)' ]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ ec2.amazonaws.com ]
            Action: sts:AssumeRole
      Path: /

  IAMPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: InstancePolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - cloudwatch:PutMetricData
              - cloudformation:DescribeStackResource
              - ec2:DescribeTags
              - autoscaling:DescribeAutoScalingInstances
              - autoscaling:DescribeLifecycleHooks
              - autoscaling:RecordLifecycleActionHeartbeat
              - autoscaling:CompleteLifecycleAction
            Resource: "*"
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogStreams
            Resource: "*"

      Roles:
        - $(IAMRole)

  SecretsBucketPolicies:
    Type: AWS::IAM::Policy
    Condition: UseSecretsBucket
    Properties:
      PolicyName: SecretsBucketPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:Get
              - s3:List*
            Resource:
              - "arn:aws:s3:::$(SecretsBucket)/*"
              - "arn:aws:s3:::$(SecretsBucket)"
      Roles:
        - $(IAMRole)

  ArtifactsBucketPolicies:
    Type: AWS::IAM::Policy
    Condition: UseArtifactsBucket
    Properties:
      PolicyName: ArtifactsBucketPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:Put*
              - s3:List*
            Resource:
              - "arn:aws:s3:::$(ArtifactsBucket)/*"
              - "arn:aws:s3:::$(ArtifactsBucket)"
      Roles:
        - $(IAMRole)

  AgentLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: $(AssociatePublicIpAddress)
      SecurityGroups: [ !If [ "CreateSecurityGroup", $(SecurityGroup), $(SecurityGroupId) ] ]
      KeyName : $(KeyName)
      IamInstanceProfile: $(IAMInstanceProfile)
      InstanceType: $(InstanceType)
      SpotPrice: !If [ "UseSpotInstances", $(SpotPrice), '$(AWS::NoValue)' ]
      ImageId : !If [
        "UseDefaultAMI",
        "$(AWSRegion2AMI[$(AWS::Region)][AMI])",
        $(ImageId)
      ]
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs: { VolumeSize: $(RootVolumeSize), VolumeType: gp2 }
      UserData: !Base64 |
        #!/bin/bash -xv
        BUILDKITE_STACK_NAME="$(AWS::StackName)" \
        BUILDKITE_SECRETS_BUCKET="$(SecretsBucket)" \
        BUILDKITE_AGENT_TOKEN="$(BuildkiteAgentToken)" \
        BUILDKITE_AGENTS_PER_INSTANCE="$(AgentsPerInstance)" \
        BUILDKITE_AGENT_RELEASE="$(BuildkiteAgentRelease)" \
        BUILDKITE_QUEUE="$(BuildkiteQueue)" \
        BUILDKITE_ELASTIC_BOOTSTRAP_SCRIPT="$(BootstrapScriptUrl)" \
        BUILDKITE_AUTHORIZED_USERS_URL="$(AuthorizedUsersUrl)" \
        BUILDKITE_ECR_POLICY=$(ECRAccessPolicy) \
        AWS_DEFAULT_REGION=$(AWS::Region) \
        AWS_REGION=$(AWS::Region) \
          /usr/local/bin/bk-install-elastic-stack.sh

        /opt/aws/bin/cfn-signal \
          --region "$(AWS::Region)" \
          --stack "$(AWS::StackName)" \
          --resource "AgentAutoScaleGroup" \
          --exit-code \$?


  # XXX: We don't even want a topic or role, but CloudFormation requires them
  # to create a lifecycle hook.
  AgentLifecycleTopic:
    Type: AWS::SNS::Topic

  AgentLifecycleHookRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ autoscaling.amazonaws.com ]
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AgentLifecyclePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: $(AgentLifecycleTopic)
      Path: /

  AgentLifecycleHook:
    Type: AWS::AutoScaling::LifecycleHook
    Properties:
      AutoScalingGroupName: $(AgentAutoScaleGroup)
      LifecycleTransition: autoscaling:EC2_INSTANCE_TERMINATING
      DefaultResult: CONTINUE
      NotificationTargetARN: $(AgentLifecycleTopic)
      RoleARN: $(AgentLifecycleHookRole[Arn])

  AgentAutoScaleGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !If [
        "CreateVpcResources",
        [ $(Subnet0), $(Subnet1) ],
        $(Subnets)
      ]
      LaunchConfigurationName: $(AgentLaunchConfiguration)
      DesiredCapacity: $(MinSize)
      MinSize: $(MinSize)
      MaxSize: $(MaxSize)
      MetricsCollection:
        - Granularity: 1Minute
          Metrics:
            - GroupMinSize
            - GroupMaxSize
            - GroupInServiceInstances
            - GroupTerminatingInstances
            - GroupPendingInstances
      TerminationPolicies:
        - OldestLaunchConfiguration
        - ClosestToNextInstanceHour
      Tags:
        - Key: Role
          Value: buildkite-agent
          PropagateAtLaunch: true
        - Key: Name
          Value: buildkite-agent
          PropagateAtLaunch: true
        - Key: BuildkiteAgentRelease
          Value: $(BuildkiteAgentRelease)
          PropagateAtLaunch: true
        - Key: BuildkiteQueue
          Value: $(BuildkiteQueue)
          PropagateAtLaunch: true

    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
        Count: $(MinSize)
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: !If [
          "AllowZeroInstancesDuringScaling",
          0,
          $(MinSize)
        ]
        MaxBatchSize: 5
        # On rollback this might have to wait for an agent to finish
        # a job. The agent's init script waits 30 minutes, so we wait
        # a maximum of 40 minutes to be safe.
        PauseTime: PT40M
        WaitOnResourceSignals: true

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: CreateSecurityGroup
    Properties:
      GroupDescription: Enable access to SSH
      VpcId: !If [ "CreateVpcResources", $(Vpc), $(VpcId) ]
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
